// Auto-generated by scripts/generate-env.js from .env — do not edit directly.
export const environment = {
  production: false,
  wsUrl: 'http://localhost:3000',
  supabase: {
    url: 'https://atmandnlqyyjaofezyig.supabase.co',
    anonKey: '***REMOVED-SUPABASE-ANON-KEY***',
  },
};
