require('dotenv').config();
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

function envFile(production, wsUrl) {
  return `// Auto-generated by scripts/generate-env.js from .env — do not edit directly.
export const environment = {
  production: ${production},
  wsUrl: '${wsUrl}',
  supabase: {
    url: '${supabaseUrl}',
    anonKey: '${supabaseAnonKey}',
  },
};
`;
}

fs.writeFileSync(
  path.join(__dirname, '../src/environments/environment.ts'),
  envFile(false, process.env.WS_URL || 'http://localhost:3000')
);
fs.writeFileSync(
  path.join(__dirname, '../src/environments/environment.prod.ts'),
  envFile(true, '') // same origin in production
);
console.log('Generated src/environments/environment{.prod}.ts from .env');
